### ISSUE TITLE
kota

### ISSUE THREAD

**Issue by duyguolmez** [limanmys/liman-samba#2]
kotalı senaryoda .bak ı dosyanın izni bozuluyor, aşağıdaki çözüm ile düzelmekte. bak dizinine gidilip acl yedeklenecek
sonra orjinal dosyaya gidilip acl yedeklenir
https://stackoverflow.com/questions/17436146/set-file-permissions-in-one-directory-to-match-another

**Comment by dogukanoksuz** [comment]
halihazırda bu çözüm uygulanmıştır
https://github.com/limanmys/liman-samba/blob/a680d052c62994cb646fb35688e20e23159a92d3/app/Controllers/SectionController.php#L434

dosya ağacının altındaki izinlerin ve opt paylasimlar klasörünün izinlerinin notion klasöründeki bilgilere göre düzenlenmesi gerekmektedir. sıfır ortam kurulup gerekli araştırma yapılmış, problem bulunamamıştır.
